### ISSUE TITLE
Possible memory leak in latest version

### ISSUE THREAD

**Issue by brian-maloney** [EOSLaoMao/elasticsearch_plugin#7] opened 2018-10-23 16:58 UTC
With the latest version, syncing against mainnet gets to around 1.5 million blocks and then nodeos is OOM-killed by the OS, on a system with 104GB RAM.  This does not happen when syncing to mongodb on a similarly-sized system.

**Comment by WLBF** [comment] 2018-10-24 02:45
I didn't meet the problem around 1.5 million, large ram usage come out around 7.2 million in my test run. It's probably caused by oversized bulk buffer, I caculate bulk buffer size by counting document number, which is not very wise. just fixed in  #5

**Comment by brian-maloney** [comment] 2018-10-24 19:28
This does look fixed with #5 - thanks!

**Comment by brian-maloney** [comment] 2018-10-25 13:04
A run last night was OOM-killed at block #6158000 with the following error:

```
Oct 25 03:46:57 es-nodeos kernel: Out of memory: Kill process 31368 (nodeos) score 812 or sacrifice child
Oct 25 03:46:57 es-nodeos kernel: Killed process 31368 (nodeos) total-vm:157843424kB, anon-rss:86821540kB, file-rss:396kB, shmem-rss:8kB
```

One comment I had from the developer of the mongo plugin was as follows:

> No. boost::asio::post uses a queue to return immediately. There is no limit to this queue, therefore they can pile up.

I am not a C++ developer so I can't comment conclusively but you might want to look into your use of that call.

**Comment by WLBF** [comment] 2018-10-26 04:05
> A run last night was OOM-killed at block #6158000 with the following error:
> 
> ```
> Oct 25 03:46:57 es-nodeos kernel: Out of memory: Kill process 31368 (nodeos) score 812 or sacrifice child
> Oct 25 03:46:57 es-nodeos kernel: Killed process 31368 (nodeos) total-vm:157843424kB, anon-rss:86821540kB, file-rss:396kB, shmem-rss:8kB
> ```
> One comment I had from the developer of the mongo plugin was as follows:
> 
> > No. boost::asio::post uses a queue to return immediately. There is no limit to this queue, therefore they can pile up.
> 
> I am not a C++ developer so I can't comment conclusively but you might want to look into your use of that call.

[https://stackoverflow.com/questions/11679125/setting-limit-on-post-queue-size-with-boost-asio](https://stackoverflow.com/questions/11679125/setting-limit-on-post-queue-size-with-boost-asio)
looks like the unlimited task queue size is the root cause. thanks for help, will reimplementation it asap.

**Comment by brian-maloney** [comment] 2018-10-26 13:30
I rebuilt my nodeos instance yesterday on Ubuntu 18.04 and it's gotten past block 8 million without the memory leak.  I'm not sure why it's behaving better on Ubuntu but at least it probably explains why your testing didn't discover it.

**Comment by WLBF** [comment] 2018-10-28 14:26
> I rebuilt my nodeos instance yesterday on Ubuntu 18.04 and it's gotten past block 8 million without the memory leak. I'm not sure why it's behaving better on Ubuntu but at least it probably explains why your testing didn't discover it.

#11 implement with another thread pool, and set the thread pool task limit equal to `elastic-queue-size`. My test run sync to 1700w without massive ram usage.

**Closed as completed** 2018-10-29 04:45 UTC
Labels: bug
